[Log]
Level = 'debug'

[WebServer]
AllowOrigins = 'http://localhost:3000,http://localhost:6688' # Default
SecureCookies = false
SessionTimeout = '15m' # Default

[WebServer.TLS]
HTTPSPort = 0 # Default
ForceRedirect = false # Default

[[EVM]]
ChainID = '51'
Enabled = true #Default
LinkContractAddress = "0x33f4212b027E22aF7e6BA21Fc572843C0D701CD1"


[[EVM.Nodes]]
name = "XdcApothem"
wsUrl = "wss://wss-apothem.go140point6.com"
httpUrl = 'https://rpc-apothem.go140point6.com/'

[Feature]
FeedsManager = false # Default
