[Log]
Level = 'debug'

[WebServer]
AllowOrigins = 'http://localhost:3000,http://localhost:6688' # Default
SecureCookies = false
SessionTimeout = '15m' # Default

[WebServer.TLS]
HTTPSPort = 0 # Default
ForceRedirect = false # Default

[[EVM]]
ChainID = '51' # Apothem
Enabled = true #Default
LinkContractAddress = "0x33f4212b027e22af7e6ba21fc572843c0d701cd1"

# ChainID = '50' # Mainnet
# Enabled = true #Default
# LinkContractAddress = "0xFf7412Ea7C8445C46a8254dFB557Ac1E48094391"

[[EVM.Nodes]]
name = "XdcApothem" # 11ppm MN-Apothem
wsUrl = "wss://ws-apothem.11ppm.com"
httpUrl = 'https://rpc-apothem.11ppm.com'

# name = "XdcMainnet" # 11ppm MN-Mainnet
# wss://ws.11ppm.com
# https://rpc.11ppm.com

# name = "XdcMainnet"
# wsUrl = "wss://ws.xinfin.network"
# httpUrl = 'https://erpc.xinfin.network'

[Feature]
FeedsManager = false # Default
